from homeassistant.const import Platform

DOMAIN = "emaux_spv150"
DEFAULT_HOST = "192.168.1.1"
PLATFORMS = [Platform.SENSOR, Platform.NUMBER, Platform.SWITCH, Platform.SELECT]

CONF_SWITCH_ENTITY = "switch_entity"
CONF_POLL_INTERVAL = "poll_interval"
CONF_GRID_POWER_ENTITY = "grid_power_entity"
CONF_SETPOINT = "setpoint"
CONF_DEAD_BAND_LOWER = "dead_band_lower"
CONF_DEAD_BAND_UPPER = "dead_band_upper"
CONF_STEP_UP = "step_up"
CONF_STEP_DOWN = "step_down"
CONF_RPM_MIN_SOLAR = "rpm_min_solar"
CONF_RPM_MAX_SOLAR = "rpm_max_solar"
CONF_PRIMING_TIME = "priming_time"
CONF_SPEED_CHANGE_INTERVAL = "speed_change_interval"

DEFAULT_POLL_INTERVAL = 30
DEFAULT_SETPOINT = 0.0
DEFAULT_DEAD_BAND_LOWER = 0.0
DEFAULT_DEAD_BAND_UPPER = 100.0
DEFAULT_STEP_UP = 300
DEFAULT_STEP_DOWN = 30
DEFAULT_RPM_MIN_SOLAR = 1400
DEFAULT_RPM_MAX_SOLAR = 3000
DEFAULT_PRIMING_TIME = 120
DEFAULT_SPEED_CHANGE_INTERVAL = 60

COMMAND_SETTLE_DELAY = 2
